application: me-deepgully
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /.*
  script: index.application

libraries:
- name: jinja2
  version: "2.6"

- name: PIL
  version: "1.1.7"
