"""database v1.3

Revision ID: 4397a3de5953
Revises: 24871ecda46d
Create Date: 2014-06-21 12:02:45.487000

"""

# revision identifiers, used by Alembic.
revision = '4397a3de5953'
down_revision = '24871ecda46d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_category', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('db_site_settings', sa.Column('theme', sa.String(length=128), nullable=True))
    op.add_column('db_site_settings', sa.Column('mirror_site', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_site_settings', 'mirror_site')
    op.drop_column('db_site_settings', 'theme')
    op.drop_column('db_category', 'hidden')
    ### end Alembic commands ###
